name: notebook
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alembic=1.5.5
  - anyio=2.1.0
  - appdirs=1.4.4
  - argon2-cffi=20.1.0
  - asdf=2.7.3
  - async_generator=1.10
  - attrs=20.3.0
  - babel=2.9.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - bleach=3.3.0
  - blinker=1.4
  - boltons=20.2.1
  - bottleneck=1.3.2
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2020.12.5
  - certipy=0.1.3
  - cffi=1.14.5
  - cftime=1.4.1
  - chardet=4.0.0
  - cryptography=3.4.4
  - curl=7.71.1
  - cycler=0.10.0
  - dbus=1.13.18
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.3.0
  - fontconfig=2.13.1
  - freetype=2.10.4
  - fs=2.4.11
  - gettext=0.19.8.1
  - glib=2.68.0
  - glib-tools=2.68.0
  - gmp=6.2.1
  - gmpy2=2.1.0b1
  - gst-plugins-base=1.18.4
  - gstreamer=1.18.4
  - h5py=3.1.0
  - hdf4=4.2.13
  - hdf5=1.10.6
  - icu=68.1
  - idna=2.10
  - importlib-metadata=3.4.0
  - importlib_metadata=3.4.0
  - importlib_resources=5.1.2
  - ipydatawidgets=4.2.0
  - ipykernel=5.5.0
  - ipympl=0.5.8
  - ipython=7.20.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jedi=0.18.0
  - jinja2=2.11.3
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter-offlinenotebook=0.2.1
  - jupyter-resource-usage=0.5.1
  - jupyter_client=6.1.11
  - jupyter_core=4.7.1
  - jupyter_server=1.4.0
  - jupyter_telemetry=0.1.0
  - jupyterhub-base=1.3.0
  - jupyterhub-singleuser=1.3.0
  - jupyterlab=2.3.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=1.2.0
  - jupyterlab_widgets=1.0.0
  - k3d=2.9.3
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcurl=7.71.1
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libglib=2.68.0
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libnetcdf=4.7.4
  - libnghttp2=1.43.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libpq=13.1
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuuid=2.32.1
  - libuv=1.41.0
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxkbcommon=1.0.3
  - libxml2=2.9.10
  - lz4-c=1.9.3
  - mako=1.1.4
  - markupsafe=1.1.1
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - meshio=4.3.8
  - mistune=0.8.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.2.1
  - mysql-common=8.0.23
  - mysql-libs=8.0.23
  - nbclassic=0.2.6
  - nbclient=0.5.2
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - ncurses=6.2
  - nest-asyncio=1.4.3
  - netcdf4=1.5.6
  - networkx=2.5
  - nodejs=15.12.0
  - notebook=6.2.0
  - nspr=4.30
  - nss=3.63
  - nteract_on_jupyter=2.1.3
  - numpy=1.20.2
  - oauthlib=3.0.1
  - olefile=0.46
  - openssl=1.1.1j
  - packaging=20.9
  - pamela=1.0.0
  - pandas=1.2.3
  - pandoc=2.11.4
  - pandocfilters=1.4.2
  - parso=0.8.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.1.2
  - pint=0.17
  - pip=21.0.1
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.16
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - pycparser=2.20
  - pycurl=7.43.0.6
  - pygments=2.8.0
  - pyjwt=2.0.1
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.8.8
  - python-dateutil=2.8.1
  - python-editor=1.0.4
  - python-json-logger=2.0.1
  - python_abi=3.8
  - pytz=2021.1
  - pyyaml=5.4.1
  - pyzmq=22.0.3
  - qt=5.12.9
  - readline=8.0
  - requests=2.25.1
  - ruamel.yaml=0.16.12
  - ruamel.yaml.clib=0.2.2
  - scipy=1.6.2
  - semantic_version=2.8.5
  - send2trash=1.5.0
  - setuptools=49.6.0
  - setuptools-scm=6.0.1
  - setuptools_scm=6.0.1
  - six=1.15.0
  - sniffio=1.2.0
  - sqlalchemy=1.3.23
  - sqlite=3.34.0
  - sympy=1.7.1
  - terminado=0.9.2
  - testpath=0.4.4
  - tk=8.6.10
  - toml=0.10.2
  - tornado=6.1
  - traitlets=5.0.5
  - traittypes=0.2.1
  - urllib3=1.26.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - weldx=0.3.3
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - xarray=0.17.0
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.9
