name: pytest
on: [push, pull_request]

jobs:
  pytest:
    name: pytest
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        py: ['3.8']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('.github/workflows/pytest.yml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: pip installs
        run: |
          pip install wheel
          pip install asdf==2.7.3 weldx==0.3.3 pytest nbval ipympl

      - name: run pytest on notebook
        run: |
          pytest --color=yes --nbval --current-env iiw2021_CXII_fabry_cagtay_01.ipynb

